### ISSUE TITLE
React Group Kanban Project 🚀

### ISSUE THREAD

**Issue by hsztan** [hsztan/Missions-and-Rockets#21]
My partner 🧑‍💻👨🏻‍💻 and I assign Kanban task cards 🃏 for each to organize our time and responsibilities. We duplicated Kanban cards from the Microverse React-Redux group project template. 😎

Project link --> [here](https://github.com/hsztan/Missions-and-Rockets/projects/1)

**Comment by KDlamini** [comment]
### Hi @hsztan, @Dangelo-JAN 🙋‍♀️,  

Great work! 💯 
Your Kanban Board is complete!
Congratulations!!!

# Status: Approved ✔️ 

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
